# Generated by Django 4.1.3 on 2022-11-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
