# Generated by Django 4.1.3 on 2022-11-23 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_autor_biografia_autor_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='libro',
            name='agno_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, default='Editorial', max_length=100, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero_literario',
            field=models.IntegerField(choices=[(1, 'Narrativa'), (2, 'Lírica'), (3, 'Dramática')], default=1, verbose_name='Género Literario'),
        ),
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(blank=True, max_length=20, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre',
            field=models.CharField(default='Nombre Libro', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripción', verbose_name='Descripción'),
        ),
    ]
