# Generated by Django 4.1.3 on 2022-11-23 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_remove_libro_titulo_libro_agno_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='agno_publicacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Año de publicación'),
        ),
    ]
