# Generated by Django 4.1.3 on 2022-11-23 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_agno_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='agno_publicacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Año de publicación'),
        ),
    ]
